services:
  api:
    build:
      context: ./
      dockerfile: ./compose/api/Dockerfile
    container_name: go_service
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./
      dockerfile: ./compose/frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000"
    networks:
      - app_network


networks:
  app_network:
